//
//  MetalImage.h
//  MetalImage
//
//  SPM umbrella header — flat directory structure for Xcode 15+ SPM compliance.
//
//  All headers live in the source tree under Framework/MetalImage/MetalImage/.
//  This umbrella exposes them via relative paths from the include/ directory.
//

#if TARGET_IPHONE_SIMULATOR
#warning <MetalImage> framework does not support SIMULATOR.
#endif

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

// The actual umbrella with all imports
#import "../MetalImage/Color/MIBrightnessFilter.h"
#import "../MetalImage/Color/MIColorMatrixFilter.h"
#import "../MetalImage/Color/MIContrastFilter.h"
#import "../MetalImage/Color/MIExposureFilter.h"
#import "../MetalImage/Color/MIGammaFilter.h"
#import "../MetalImage/Color/MILevelsFilter.h"
#import "../MetalImage/Color/MISaturationFilter.h"
#import "../MetalImage/Color/MIRGBFilter.h"
#import "../MetalImage/Color/MIHSBFilter.h"
#import "../MetalImage/Color/MIHueFilter.h"
#import "../MetalImage/Color/MIMonochromeFilter.h"
#import "../MetalImage/Color/MIFalseColorFilter.h"
#import "../MetalImage/Color/MIHazeFilter.h"
#import "../MetalImage/Color/MISepiaFilter.h"
#import "../MetalImage/Color/MIColorInvertFilter.h"
#import "../MetalImage/Color/MIGrayscaleFilter.h"
#import "../MetalImage/Color/MILuminanceThresholdFilter.h"
#import "../MetalImage/Color/MIAdaptiveThresholdFilter.h"
#import "../MetalImage/Color/MISolarizeFilter.h"
#import "../MetalImage/Color/MIAverageLuminanceThresholdFilter.h"
#import "../MetalImage/Color/MIHistogramGenerator.h"
#import "../MetalImage/Color/MIHistogramFilter.h"
#import "../MetalImage/Color/MIHighlightShadowFilter.h"
#import "../MetalImage/Color/MILookupFilter.h"
#import "../MetalImage/Color/MIOpacityFilter.h"
#import "../MetalImage/Color/MIChromaKeyFilter.h"
#import "../MetalImage/Color/MIWhiteBalanceFilter.h"
#import "../MetalImage/Color/MILuminanceRangeFilter.h"

#import "../MetalImage/ImageProcessing/MITransformFilter.h"
#import "../MetalImage/ImageProcessing/MICropFilter.h"
#import "../MetalImage/ImageProcessing/MIGaussianBlurFilter.h"
#import "../MetalImage/ImageProcessing/MISharpenFilter.h"
#import "../MetalImage/ImageProcessing/MIMedianFilter.h"
#import "../MetalImage/ImageProcessing/MI3x3ConvolutionFilter.h"
#import "../MetalImage/ImageProcessing/MILaplacianFilter.h"
#import "../MetalImage/ImageProcessing/MISobelEdgeDetectionFilter.h"
#import "../MetalImage/ImageProcessing/MIThresholdEdgeDetectionFilter.h"
#import "../MetalImage/ImageProcessing/MIDirectionalSobelEdgeDetectionFilter.h"
#import "../MetalImage/ImageProcessing/MIDirectionalNonMaximumSuppressionFilter.h"
#import "../MetalImage/ImageProcessing/MIWeakPixelInclusionFilter.h"
#import "../MetalImage/ImageProcessing/MIPrewittEdgeDetectionFilter.h"
#import "../MetalImage/ImageProcessing/MIXYDerivativeFilter.h"
#import "../MetalImage/ImageProcessing/MIFASTCornerDetectionFilter.h"
#import "../MetalImage/ImageProcessing/MINonMaximumSuppressionFilter.h"
#import "../MetalImage/ImageProcessing/MICrosshairGenerator.h"
#import "../MetalImage/ImageProcessing/MIDilationFilter.h"
#import "../MetalImage/ImageProcessing/MIRGBDilationFilter.h"
#import "../MetalImage/ImageProcessing/MIErosionFilter.h"
#import "../MetalImage/ImageProcessing/MIRGBErosionFilter.h"
#import "../MetalImage/ImageProcessing/MIOpeningFilter.h"
#import "../MetalImage/ImageProcessing/MIRGBOpeningFilter.h"
#import "../MetalImage/ImageProcessing/MIClosingFilter.h"
#import "../MetalImage/ImageProcessing/MIRGBClosingFilter.h"
#import "../MetalImage/ImageProcessing/MIColorPackingFilter.h"
#import "../MetalImage/ImageProcessing/MILocalBinaryPatternFilter.h"
#import "../MetalImage/ImageProcessing/MIColorLocalBinaryPatternFilter.h"
#import "../MetalImage/ImageProcessing/MILanczosResamplingFilter.h"
#import "../MetalImage/ImageProcessing/MILowPassFilter.h"
#import "../MetalImage/ImageProcessing/MIHighPassFilter.h"
#import "../MetalImage/ImageProcessing/MIBilateralFilter.h"
#import "../MetalImage/ImageProcessing/MIMaskBilateralFilter.h"
#import "../MetalImage/ImageProcessing/MIHistogramEqualizationFilter.h"
#import "../MetalImage/ImageProcessing/MIAdaptiveLuminanceFilter.h"
#import "../MetalImage/ImageProcessing/MICannyEdgeDetectionFilter.h"

#import "../MetalImage/Blend/MISourceOverBlendFilter.h"
#import "../MetalImage/Blend/MIColorBurnBlendFilter.h"
#import "../MetalImage/Blend/MIColorDodgeBlendFilter.h"
#import "../MetalImage/Blend/MIDarkenBlendFilter.h"
#import "../MetalImage/Blend/MIDifferenceBlendFilter.h"
#import "../MetalImage/Blend/MIDissolveBlendFilter.h"
#import "../MetalImage/Blend/MIExclusionBlendFilter.h"
#import "../MetalImage/Blend/MIHardLightBlendFilter.h"
#import "../MetalImage/Blend/MISoftLightBlendFilter.h"
#import "../MetalImage/Blend/MILightenBlendFilter.h"
#import "../MetalImage/Blend/MIAddBlendFilter.h"
#import "../MetalImage/Blend/MISubtractBlendFilter.h"
#import "../MetalImage/Blend/MIDivideBlendFilter.h"
#import "../MetalImage/Blend/MIMultiplyBlendFilter.h"
#import "../MetalImage/Blend/MIOverlayBlendFilter.h"
#import "../MetalImage/Blend/MIScreenBlendFilter.h"
#import "../MetalImage/Blend/MIChromaKeyBlendFilter.h"
#import "../MetalImage/Blend/MIAlphaBlendFilter.h"
#import "../MetalImage/Blend/MINormalBlendFilter.h"
#import "../MetalImage/Blend/MIColorBlendFilter.h"
#import "../MetalImage/Blend/MIHueBlendFilter.h"
#import "../MetalImage/Blend/MISaturationBlendFilter.h"
#import "../MetalImage/Blend/MILuminosityBlendFilter.h"
#import "../MetalImage/Blend/MILinearBurnBlendFilter.h"
#import "../MetalImage/Blend/MIMaskFilter.h"

#import "../MetalImage/Effects/MIPerlinNoiseFilter.h"
#import "../MetalImage/Effects/MIPixellateFilter.h"
#import "../MetalImage/Effects/MIPolkaDotFilter.h"
#import "../MetalImage/Effects/MIHalftoneFilter.h"
#import "../MetalImage/Effects/MIPolarPixellateFilter.h"
#import "../MetalImage/Effects/MICrosshatchFilter.h"
#import "../MetalImage/Effects/MICGAColorspaceFilter.h"
#import "../MetalImage/Effects/MIPosterizeFilter.h"
#import "../MetalImage/Effects/MISwirlFilter.h"
#import "../MetalImage/Effects/MIBulgeDistortionFilter.h"
#import "../MetalImage/Effects/MIPinchDistortionFilter.h"
#import "../MetalImage/Effects/MIStretchDistortionFilter.h"
#import "../MetalImage/Effects/MISphereRefractionFilter.h"
#import "../MetalImage/Effects/MIGlassSphereFilter.h"
#import "../MetalImage/Effects/MIKuwaharaFilter.h"
#import "../MetalImage/Effects/MIKuwaharaRadius3Filter.h"
#import "../MetalImage/Effects/MIVignetteFilter.h"
#import "../MetalImage/Effects/MIJFAVoronoiFilter.h"
#import "../MetalImage/Effects/MIMosaicFilter.h"
#import "../MetalImage/Effects/MIVoronoiConsumerFilter.h"

#import "../MetalImage/Matrix/MetalMatrixBuffers.h"
#import "../MetalImage/Matrix/BlasMatrixMult.h"
#import "../MetalImage/Matrix/MetalMatrixMult.h"

#import "../MetalImage/MetalDevice.h"
#import "../MetalImage/MetalImageColorConversion.h"
#import "../MetalImage/MetalImageContext.h"
#import "../MetalImage/MetalImageDebugView.h"
#import "../MetalImage/MetalImageFilter.h"
#import "../MetalImage/MetalImageRenderResource.h"
#import "../MetalImage/MetalImageBuffer.h"
#import "../MetalImage/MetalImageFilterExtension.h"
#import "../MetalImage/MetalImageTwoPassFilter.h"
#import "../MetalImage/MITwoPassTextureSamplingFilter.h"
#import "../MetalImage/MI3x3TextureSamplingFilter.h"
#import "../MetalImage/MetalImageTwoInputFilter.h"
#import "../MetalImage/MetalImageFilterGroup.h"
#import "../MetalImage/MetalImageFunction.h"
#import "../MetalImage/MetalImageGlobal.h"
#import "../MetalImage/MetalImageTypes.h"
#import "../MetalImage/MetalImageInput.h"
#import "../MetalImage/MetalImageKernel.h"
#import "../MetalImage/MetalImageTwoInputKernel.h"
#import "../MetalImage/MetalImageOutput.h"
#import "../MetalImage/MetalImagePicture.h"
#import "../MetalImage/MetalImageTexture.h"
#import "../MetalImage/MetalImageTextureCache.h"
#import "../MetalImage/MetalImageVideoCamera.h"
#import "../MetalImage/MetalImageView.h"
#import "../MetalImage/UIImage+Texture.h"
#import "../MetalImage/MetalImageMath.h"
